### ISSUE TITLE
get_traffic_infoのWiki

### ISSUE THREAD

**Issue by eggplants** [unyacat/westjr#37]
[get_traffic_info()](https://github.com/unyacat/westjr/wiki/get_traffic_info()) の異常時レスポンスをWayback Machine上で見つけたのでWikiに追記していただけるといいと思います。

https://web.archive.org/web/20200223132721/https://www.train-guide.westjr.co.jp/api/v3/area_kinki_trafficinfo.json

https://web.archive.org/web/20230124063108/https://www.train-guide.westjr.co.jp/api/v3/area_kinki_trafficinfo.json

**Comment by unyacat** [comment]
いつもお世話になっております．
新しい情報の報告ありがとうございます．追加させていただきました．
また，eggplants氏の多大なる貢献によって更新された分を反映し，Wikiの整備を行いました．
本当にありがとうございます．
