### ISSUE TITLE
pre-commit.ci

### ISSUE THREAD

**Issue by eggplants** [unyacat/westjr#8]
<https://pre-commit.ci>にこのリポジトリを登録すると、pre-commitを速く、簡単に回せます。ご検討ください。

また有効化されましたら、[ここ](https://github.com/unyacat/westjr/blob/31fd1948ea12cd55632427452d37e8a585debbeb/.github/workflows/test.yml#L33-L35)を削除してください。

**Comment by unyacat** [comment]
ちょうどpre-commit.ciについて調べておりました．
有効化しました．
非常に助かります．
